### ISSUE TITLE
请问在dialog中的按钮加上焦点时，怎么处理

### ISSUE THREAD

**Issue by idxiu** [RyanHuen/AndroidTVFocus#1]
![111515101146](https://user-images.githubusercontent.com/12675437/40032872-7b803cee-5828-11e8-84b0-33202db52fef.png)

使用中发现获取焦点时，其中一个按钮被隐藏了

![image](https://user-images.githubusercontent.com/12675437/40032754-16443e84-5828-11e8-95d7-c7455f52de40.png)

**Comment by RyanHuen** [comment]
使用的什么效果？看样子像是onDraw()的次数不够     你可以尝试增加动画时长看看

**Comment by RyanHuen** [comment]
onDraw问题其实猜测可能是Dialog显示的时候，你让Dialog中的Button获取焦点过快，你可以Handler来postdelay一下获取焦点的时间，应该就没问题了
