### ISSUE TITLE
嵌套ScrollView时焦点view不会横着滑动，造成界面UI混乱

### ISSUE THREAD

**Issue by idxiu** [RyanHuen/AndroidTVFocus#2]
![image](https://user-images.githubusercontent.com/12675437/41136388-a2515f5e-6b08-11e8-98a2-ff15bb5126eb.png)

![image](https://user-images.githubusercontent.com/12675437/41136468-00558238-6b09-11e8-8b76-409f957c9e94.png)

移动后
![image](https://user-images.githubusercontent.com/12675437/41136488-13f8644a-6b09-11e8-98f5-a71e0c43c461.png)

**Comment by RyanHuen** [comment]
ScrollView这个问题目前暂时没想到解决方案，因为Scroll监听不像ListView和RecyclerView一样有IDLE状态标识。所以目前没有太好的方案，建议用RecyclerView或者ListView吧
